package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin connectivity, io.flutter.plugins.connectivity.ConnectivityPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new br.com.prates.flutter_internet_signal.FlutterInternetSignalPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_internet_signal, br.com.prates.flutter_internet_signal.FlutterInternetSignalPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new klydra.wifi_hunter.WiFiHunterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin wifi_hunter, klydra.wifi_hunter.WiFiHunterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.wifi_info_flutter.WifiInfoFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin wifi_info_flutter, io.flutter.plugins.wifi_info_flutter.WifiInfoFlutterPlugin", e);
    }
  }
}
